### ISSUE TITLE
Ragnar Joint_states topic not reflecting robots motions

### ISSUE THREAD

**Issue by shisha101** [shisha101/ROSRagnarEDU#3]
When the robot is connected via 

```
roslaunch ragnar_support bringup.launch robot_ip:=10.0.1.39
```

the **joint_states** topic is not being updated with any values, even if the robot is moved manually

```
header: 
  seq: 2775
  stamp: 
    secs: 1455896181
    nsecs: 724430882
  frame_id: base_link
name: ['joint_1', 'joint_2', 'joint_3', 'joint_4']
position: [-0.0, -0.0, -0.0, -0.0]
velocity: [-0.0, -0.0, -0.0, -0.0]
effort: [-87.26646259971648, -87.26646259971648, -87.26646259971648, -87.26646259971648]

```
